<?php

/**
 * @file
 * Functions to support theming in the Custom Elements theme.
 */

define('THEME_ROOT', dirname(__FILE__));
define('TAG_PREFIX', 'ue');

/**
 * Implements hook_preprocess().
 */
function ce_preprocess(&$variables, $hook): void {
  // Add custom element tag prefix.
  $variables['tagname_prefix'] = TAG_PREFIX;
  $variables['tagname'] = TAG_PREFIX . '-' . str_replace('_', '-', $hook);
}
