name: Deploy to Preview

on:
  push:
    branches:
      - preview

jobs:
  deploy_drupal:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # SETUP PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: https://registry.npmjs.org/

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      # Setup Docker
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # CACHE
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-npm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # BUILD
      - name: Install Drupal
        run: composer install --verbose --prefer-dist --no-progress --no-interaction --no-dev --optimize-autoloader

      - name: Build FE
        run: pnpm build

      # DEPLOY
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: '.'
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/ueberbit/uedev:preview
